### ISSUE TITLE
Epic Fail when clicking "<<" with not property selected

### ISSUE THREAD

**Issue by bersbersbers** [suever/dicomSort#31]
Title says it all, I guess. That's v2.1.9 on Windows 10.

Traceback (most recent call last):

  File "C:\Users\IEUser\dicomsort\gui\widgets.py", line 712, in DeselectItem

  File "C:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 12915, in Delete

PyAssertionError: C++ assertion "pos < GetCount()" failed at ..\..\src\common\ctrlsub.cpp(111) in wxItemContainer::Delete(): invalid index

**Comment by suever** [comment]
Should be fixed and will be made available as part of v2.1.10
